import { Public_Sans } from 'next/font/google';
import "./globals.css";
import "./desktop.css";
import "./responsive.css";
import { ThemeModeScript } from 'flowbite-react';
import RipplesBackground from '@/components/RipplesBackground';
import ChatWrapper from "@/components/ChatWrapper";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const publicSans = Public_Sans({
  subsets: ['latin'],
  variable: '--font-public-sans',
  weight: ['300', '400', '500', '600', '700'], // Optional: choose weights you need
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={publicSans.variable}>
        <div id="root">
          <div className="transition-opacity duration-700 opacity-100 background-image"
            style={{
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              width: '100%',
              height: '100vh',
              overflow: 'hidden',
              overflowY: 'auto',
              position: 'static',
            }}>
            <RipplesBackground />
            <Header />
            <div className="content-wrapper">{children}</div>
            {/* <ChatWrapper /> */}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}


